name: CDK Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
  
      - name: Run CDK Build and Test
        run: | 
          npm install
          cd resources/cf-url-rewriter
          npm install
          cd -
          npm run build
